using GameServer.Net.Sealed;

namespace GameServer.Tests.Net;

/// <summary>
/// Cross-implementation vector for the ADR-25 identity signature. The identical constants
/// are asserted by <c>shared/sealed/interop_test.go</c> (<c>TestInteropIdentityVector</c>).
/// </summary>
/// <remarks>
/// <para>
/// <b>Why a vector and not a round-trip.</b> Each side signing and verifying its own bytes
/// proves only that it agrees with itself, which a subtly wrong implementation also does,
/// silently. Ed25519 is deterministic, so one key over one input gives one signature
/// everywhere — which makes "the C# server and the Go client produce the same bytes" a
/// testable claim rather than an aspiration.
/// </para>
/// <para>
/// The failure this prevents has no error message in production: a client whose signature
/// check never passes refuses every session, and nothing in any log names encryption. The
/// same shape as the sealed-handshake divergence <see cref="SealedInteropTests"/> guards.
/// </para>
/// <para>
/// The X25519 keys and the jti are <see cref="SealedInteropTests"/>'s, unchanged, so the
/// transcript here is the SAME transcript the binding and the direction keys are pinned
/// over. That is ADR-25 decision 3 made mechanical: if a future edit alters the transcript,
/// this vector stops reproducing at the same moment ADR-22's does.
/// </para>
/// </remarks>
public class ServerIdentityInteropTests
{
    private const string ClientPublicHex = "8520f0098930a754748b7ddcb43ef75a0dbf3a0d26381af4eba4a98eaa9b4e6a";
    private const string ServerPublicHex = "de9edb7d7b7dc1b4d35b61c2ece435373f8343c85b78674dadfc7e146f882b4f";
    private const string Jti = "interop-jti-0001";

    /// <summary>Arbitrary but FIXED Ed25519 seed; everything below follows from it.</summary>
    private const string IdentitySeedHex =
        "0102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f20";

    private const string IdentityPublicHex =
        "79b5562e8fe654f94078b112e8a98ba7901f853ae695bed7e0e3910bad049664";

    private const string IdentityInputHex =
        "6375766172612f7365616c65642d6964656e746974792f763100" +
        "6375766172612f7365616c65642d68616e647368616b652f763100" +
        "696e7465726f702d6a74692d3030303100" +
        "8520f0098930a754748b7ddcb43ef75a0dbf3a0d26381af4eba4a98eaa9b4e6a" +
        "de9edb7d7b7dc1b4d35b61c2ece435373f8343c85b78674dadfc7e146f882b4f" +
        "00" +
        "79b5562e8fe654f94078b112e8a98ba7901f853ae695bed7e0e3910bad049664";

    private const string IdentitySignatureHex =
        "73b55ddc68679d0694bb1602c7422a6a98941354a82a37c84fa8fe3181c7467d" +
        "abb9590f380ce33dfe298daa33ea5c9421cead03a6764bb34b37c85c67d37a0e";

    private static byte[] Hex(string s) => Convert.FromHexString(s);

    private static ServerIdentity VectorIdentity()
        // Ed25519's 32-byte seed IS the private key in BouncyCastle's parameterisation,
        // the same convention crypto/ed25519.NewKeyFromSeed uses in Go.
        => ServerIdentity.FromPrivate(Hex(IdentitySeedHex));

    private static byte[] VectorTranscript()
        => SealedHandshake.Transcript(Jti, Hex(ClientPublicHex), Hex(ServerPublicHex));

    [Fact]
    public void TheSeedDerivesTheSamePublicKeyGoDerives()
    {
        Assert.Equal(IdentityPublicHex, Convert.ToHexString(VectorIdentity().PublicKey).ToLowerInvariant());
    }

    /// <summary>
    /// The signed input, byte for byte — asserted separately from the signature so a
    /// divergence names the step that diverged instead of only the end result.
    /// </summary>
    [Fact]
    public void TheSignedInputIsByteIdenticalToGos()
    {
        byte[] input = ServerIdentity.IdentityInput(VectorTranscript(), VectorIdentity().PublicKey);
        Assert.Equal(IdentityInputHex, Convert.ToHexString(input).ToLowerInvariant());

        // And the transcript is in there verbatim, which is the promise that keeps
        // ADR-22's binding and key vectors describing this same handshake.
        Assert.Contains(Convert.ToHexString(VectorTranscript()).ToLowerInvariant(), IdentityInputHex);
    }

    [Fact]
    public void TheSignatureIsByteIdenticalToGos()
    {
        byte[] signature = VectorIdentity().Sign(VectorTranscript());
        Assert.Equal(IdentitySignatureHex, Convert.ToHexString(signature).ToLowerInvariant());
    }

    /// <summary>
    /// And this side verifies the signature Go produced — the direction that actually ships,
    /// inverted: in production C# signs and the client verifies, so proving C# accepts the
    /// Go-generated bytes proves the two verifiers agree about the same 64 bytes.
    /// </summary>
    [Fact]
    public void TheGoGeneratedSignatureVerifiesHere()
    {
        Assert.True(ServerIdentity.Verify(
            Hex(IdentityPublicHex), VectorTranscript(), Hex(IdentitySignatureHex)));
    }

    /// <summary>
    /// The vector's negative half. ADR-25 decision 8: assert the NEGATIVE case, because a
    /// verifier that accepts everything reproduces every positive vector there is.
    /// </summary>
    [Fact]
    public void AOneBitChangeToTheVectorSignatureIsRejected()
    {
        byte[] tampered = Hex(IdentitySignatureHex);
        tampered[0] ^= 0x01;
        Assert.False(ServerIdentity.Verify(Hex(IdentityPublicHex), VectorTranscript(), tampered));
    }
}
