using System.Security.Cryptography;
using System.Text;
using GameServer.Input;
using GameServer.Net;
using GameServer.Net.Transport;
using GameServer.Server;
using GameServer.World;
using Microsoft.Extensions.Logging.Abstractions;
using RpgMmo.Wire.V1;
using Shared.GameLogic.Components;

namespace GameServer.Tests.Snapshot;

/// <summary>
/// Proof that restructuring the snapshot walk does not change a single byte on the wire.
///
/// <para><b>Why a digest and not assertions.</b> Stage 3 rewrites the producer of the
/// encoder's input. "The wire is unchanged" is the invariant most at risk and the one an
/// assertion about counts or positions would not actually catch — an ordering change, a
/// one-tick shift in when a despawn lands, or a keyframe landing on a different tick are
/// all invisible to a spot check and all break a client. So this drives a fully
/// deterministic scenario through the real <see cref="TickLoop"/> and hashes the exact
/// bytes of every snapshot envelope every connection would receive, in order.</para>
///
/// <para><b>The fixture was generated before the refactor and is not regenerated by it.</b>
/// It is the pre-change wire output. If a change moves a byte, this fails with the two
/// digests; regenerating the constant to make it pass is the one thing that would destroy
/// its value, so the expected digest is written here as a literal rather than read from a
/// file anybody could rewrite in passing.</para>
///
/// <para><b>Determinism.</b> The enemy spawner is disabled — it draws from
/// <c>Random.Shared</c>, so any scenario including it is unrepeatable by construction.
/// Everything else in the tick is a pure function of the scripted inputs.</para>
/// </summary>
public class SnapshotByteIdentityTests
{
    private const int TickRate = 15;
    private const int Ticks = 120;   // > 3 keyframe intervals at the default of 30
    private const int Players = 6;

    private sealed class NullTransport : ITransportConnection
    {
        public Stream Stream { get; } = Stream.Null;
        public string RemoteEndPoint => "wire-fixture";
        public void Close() { }
        public void Dispose() { }
    }

    /// <summary>
    /// Run the scenario and return a digest over every snapshot envelope, plus a
    /// human-readable trace of the first few for when the digest disagrees and someone
    /// has to find out why.
    /// </summary>
    private static (string digest, string head) RunScenario(WireEncoding encoding)
    {
        using var world = new EcsWorld();
        var connections = new ConnectionManager();
        var handler = new InputHandler(world, NullLogger.Instance, null, TickRate, MapBounds.Default);

        // simulationPhase: null — see the class remarks on determinism.
        var loop = new TickLoop(
            world, handler, connections, TickRate, GameConstants.DefaultAoiRadius,
            NullLogger.Instance, metrics: null,
            keyframeInterval: GameConstants.DefaultKeyframeInterval, simulationPhase: null);

        var ids = new string[Players];
        var states = new SnapshotDeltaState[Players];

        for (int i = 0; i < Players; i++)
        {
            ids[i] = $"p{i}";
            // Spread across the AOI boundary so some pairs see each other and some do not,
            // and so that movement makes entities enter and leave view.
            world.AddEntity(TestHelpers.CreatePlayer(ids[i],
                x: (i - Players / 2f) * (GameConstants.DefaultAoiRadius / 2f),
                y: 0f, speed: 4f));
            connections.Add(new Connection(ids[i], new NullTransport(), NullLogger.Instance, encoding));
        }

        // A few static mobs so despawn/respawn transitions appear in the deltas.
        for (int i = 0; i < 5; i++)
        {
            world.AddEntity(TestHelpers.CreateMob($"m{i}", x: i * 3f, y: 2f));
        }

        // Shadow encoders: one per viewer, fed the same AOI the tick loop feeds its own.
        // The tick loop's envelopes go into a null transport, so the bytes are reproduced
        // here from the same public inputs rather than intercepted from the socket.
        for (int i = 0; i < Players; i++)
        {
            states[i] = new SnapshotDeltaState(SnapshotDeltaState.PhaseFor(ids[i]));
        }

        var sha = IncrementalHash.CreateHash(HashAlgorithmName.SHA256);
        var head = new StringBuilder();

        for (int t = 1; t <= Ticks; t++)
        {
            // Scripted, deterministic input: each player walks a different fixed heading,
            // reversing on a per-player period so they cross each other's AOI repeatedly.
            for (int i = 0; i < Players; i++)
            {
                float dir = ((t / (8 + i)) % 2 == 0) ? 1f : -1f;
                world.PushInput(ids[i], new InputData((ulong)t, dir, dir * 0.5f, null));
            }

            loop.TickOnce();

            for (int i = 0; i < Players; i++)
            {
                world.TryGetSnapshotAnchor(ids[i], out Vec2 anchor, out ulong ackTick);
                List<EntityState> nearby =
                    world.GetEntitiesInRange(anchor, GameConstants.DefaultAoiRadius);

                SnapshotMessage msg = states[i].Encode(
                    loop.CurrentTick, ackTick, nearby, GameConstants.DefaultKeyframeInterval,
                    intern: encoding == WireEncoding.Proto);

                byte[] frame = WireProtocol.Encode(
                    WireProtocol.NewEnvelope(MsgType.Snapshot, msg, encoding));

                sha.AppendData(frame);
                if (head.Length < 400)
                {
                    head.Append($"t{t} {ids[i]} full={msg.Full} n={msg.Entities.Count} " +
                                $"rm={msg.Removed.Count} bytes={frame.Length}\n");
                }
            }
        }

        return (Convert.ToHexString(sha.GetHashAndReset()), head.ToString());
    }

    /// <summary>
    /// Protobuf is the production encoding and the one with entity-id interning, whose
    /// handle allocation depends on the order entities arrive from the AOI walk — the
    /// single most order-sensitive thing downstream of stage 3.
    /// </summary>
    [Fact]
    public void ProtobufSnapshotStream_IsByteIdenticalToThePreRefactorFixture()
    {
        const string expected = "5E31830689214B517284D7D9C5E9336B9ADBAD681B11EAF896980D60686C61CB";

        (string digest, string head) = RunScenario(WireEncoding.Proto);

        Assert.True(expected == digest,
            $"Protobuf snapshot stream changed.\nexpected {expected}\nactual   {digest}\n" +
            $"first snapshots:\n{head}");
    }

    /// <summary>
    /// The legacy JSON encoding is still accepted on the wire (ADR-9) and never interns,
    /// so it fails differently from Protobuf and is worth pinning separately.
    /// </summary>
    [Fact]
    public void JsonSnapshotStream_IsByteIdenticalToThePreRefactorFixture()
    {
        const string expected = "24D8C5C2AB12909864D9BB4ACE6CB629AC9B1DDD0DDB3DF09B8DD24AF11A293C";

        (string digest, string head) = RunScenario(WireEncoding.Json);

        Assert.True(expected == digest,
            $"JSON snapshot stream changed.\nexpected {expected}\nactual   {digest}\n" +
            $"first snapshots:\n{head}");
    }

    /// <summary>The scenario must actually exercise keyframes, deltas and despawns —
    /// a digest over a stream of empty snapshots would pass any refactor.</summary>
    [Fact]
    public void TheScenarioExercisesKeyframesDeltasAndDespawns()
    {
        (_, string head) = RunScenario(WireEncoding.Proto);

        Assert.Contains("full=True", head);
        Assert.Contains("full=False", head);
        Assert.True(head.Length > 0);
    }
}
