using Google.Protobuf;
using Sgl = Shared.GameLogic.Gameplay;
using Pb = RpgMmo.Gameplay.V1;

namespace GameServer.Tests.Gameplay;

/// <summary>
/// ADR-30.4: the dependency-free codec in Shared.GameLogic/Gameplay must be byte-compatible
/// with protoc output for gameplay.proto, both ways. The Pb types are generated by
/// <c>generate.sh</c> beside this file; the Sgl types are what the server and the Unity
/// client actually run.
/// </summary>
public class GameplayCodecParityTests
{
    // ── Fixtures ────────────────────────────────────────────────────────────────

    private static readonly string[] Strings =
    {
        "",
        "a",
        "inst_0001",
        "héllo wörld — ✓",                 // multi-byte UTF-8
        "\U0001F5E1 sword",                 // 4-byte UTF-8 (surrogate pair in UTF-16)
        new string('x', 127),               // length prefix exactly 1 byte
        new string('y', 128),               // length prefix 2 bytes
        new string('z', 20000),             // length prefix 3 bytes
    };

    private static readonly uint[] UInts = { 0u, 1u, 127u, 128u, 16383u, 16384u, 0x7FFFFFFFu, uint.MaxValue };

    private static Pb.ItemStack PbStack(int seed)
    {
        return new Pb.ItemStack
        {
            InstanceId = Strings[seed % Strings.Length],
            ItemId = Strings[(seed + 3) % Strings.Length],
            Quantity = UInts[seed % UInts.Length],
            Container = seed % 2 == 0 ? Sgl.ItemContainers.Bag : Sgl.ItemContainers.Equipped,
            Slot = seed % 3 == 0 ? "" : "weapon",
            BagIndex = UInts[(seed + 5) % UInts.Length],
        };
    }

    private static Sgl.ItemStack ToSgl(Pb.ItemStack p) => new()
    {
        InstanceId = p.InstanceId,
        ItemId = p.ItemId,
        Quantity = p.Quantity,
        Container = p.Container,
        Slot = p.Slot,
        BagIndex = p.BagIndex,
    };

    private static Sgl.InventoryView ToSgl(Pb.InventoryView p)
    {
        var v = new Sgl.InventoryView();
        foreach (var i in p.Items) v.Items.Add(ToSgl(i));
        return v;
    }

    private static void AssertEqual(Pb.ItemStack expected, Sgl.ItemStack actual)
    {
        Assert.Equal(expected.InstanceId, actual.InstanceId);
        Assert.Equal(expected.ItemId, actual.ItemId);
        Assert.Equal(expected.Quantity, actual.Quantity);
        Assert.Equal(expected.Container, actual.Container);
        Assert.Equal(expected.Slot, actual.Slot);
        Assert.Equal(expected.BagIndex, actual.BagIndex);
    }

    private static void AssertEqual(Pb.InventoryView expected, Sgl.InventoryView actual)
    {
        Assert.Equal(expected.Items.Count, actual.Items.Count);
        for (int i = 0; i < expected.Items.Count; i++) AssertEqual(expected.Items[i], actual.Items[i]);
    }

    private static Pb.InventoryView PbView(int count, int seed)
    {
        var v = new Pb.InventoryView();
        for (int i = 0; i < count; i++) v.Items.Add(PbStack(seed + i));
        return v;
    }

    public static TheoryData<int> Seeds()
    {
        var d = new TheoryData<int>();
        for (int i = 0; i < 24; i++) d.Add(i);
        return d;
    }

    // ── Encode parity: SGL bytes == protoc bytes; decode both ways ───────────────

    [Fact]
    public void InventoryRequest_EncodesToZeroBytes_LikeProtoc()
    {
        Assert.Empty(new Pb.InventoryRequest().ToByteArray());
        Assert.Empty(new Sgl.InventoryRequest().ToByteArray());
        Assert.True(Sgl.InventoryRequest.TryRead(ReadOnlySpan<byte>.Empty, out _));
    }

    [Theory]
    [MemberData(nameof(Seeds))]
    public void PickupRequest_Parity(int seed)
    {
        var pb = new Pb.PickupRequest { EntityId = Strings[seed % Strings.Length] };
        var sgl = new Sgl.PickupRequest { EntityId = pb.EntityId };

        byte[] expected = pb.ToByteArray();
        Assert.Equal(expected, sgl.ToByteArray());

        Assert.True(Sgl.PickupRequest.TryRead(expected, out var decoded));
        Assert.Equal(pb.EntityId, decoded!.EntityId);
        Assert.Equal(pb, Pb.PickupRequest.Parser.ParseFrom(sgl.ToByteArray()));
    }

    [Theory]
    [MemberData(nameof(Seeds))]
    public void EquipRequest_Parity(int seed)
    {
        var pb = new Pb.EquipRequest
        {
            InstanceId = Strings[seed % Strings.Length],
            Slot = Strings[(seed + 1) % Strings.Length],
        };
        var sgl = new Sgl.EquipRequest { InstanceId = pb.InstanceId, Slot = pb.Slot };

        byte[] expected = pb.ToByteArray();
        Assert.Equal(expected, sgl.ToByteArray());

        Assert.True(Sgl.EquipRequest.TryRead(expected, out var decoded));
        Assert.Equal(pb.InstanceId, decoded!.InstanceId);
        Assert.Equal(pb.Slot, decoded.Slot);
        Assert.Equal(pb, Pb.EquipRequest.Parser.ParseFrom(sgl.ToByteArray()));
    }

    [Theory]
    [MemberData(nameof(Seeds))]
    public void UnequipRequest_Parity(int seed)
    {
        var pb = new Pb.UnequipRequest { Slot = Strings[seed % Strings.Length] };
        var sgl = new Sgl.UnequipRequest { Slot = pb.Slot };

        byte[] expected = pb.ToByteArray();
        Assert.Equal(expected, sgl.ToByteArray());

        Assert.True(Sgl.UnequipRequest.TryRead(expected, out var decoded));
        Assert.Equal(pb.Slot, decoded!.Slot);
        Assert.Equal(pb, Pb.UnequipRequest.Parser.ParseFrom(sgl.ToByteArray()));
    }

    [Theory]
    [MemberData(nameof(Seeds))]
    public void UseItemRequest_Parity(int seed)
    {
        var pb = new Pb.UseItemRequest { InstanceId = Strings[seed % Strings.Length] };
        var sgl = new Sgl.UseItemRequest { InstanceId = pb.InstanceId };

        byte[] expected = pb.ToByteArray();
        Assert.Equal(expected, sgl.ToByteArray());

        Assert.True(Sgl.UseItemRequest.TryRead(expected, out var decoded));
        Assert.Equal(pb.InstanceId, decoded!.InstanceId);
        Assert.Equal(pb, Pb.UseItemRequest.Parser.ParseFrom(sgl.ToByteArray()));
    }

    [Theory]
    [MemberData(nameof(Seeds))]
    public void ItemStack_Parity(int seed)
    {
        Pb.ItemStack pb = PbStack(seed);
        Sgl.ItemStack sgl = ToSgl(pb);

        byte[] expected = pb.ToByteArray();
        Assert.Equal(expected, sgl.ToByteArray());

        Assert.True(Sgl.ItemStack.TryRead(expected, out var decoded));
        AssertEqual(pb, decoded!);
        Assert.Equal(pb, Pb.ItemStack.Parser.ParseFrom(sgl.ToByteArray()));
    }

    [Theory]
    [InlineData(0)]
    [InlineData(1)]
    [InlineData(3)]
    [InlineData(17)]
    [InlineData(64)]
    public void InventoryView_Parity_IncludingMultiByteNestedLengths(int count)
    {
        // Strings[7] is 20000 bytes, so any view holding seed 7 or 4 (ItemId = Strings[7])
        // nests a message whose length prefix is 3 bytes -- the case where the writer has to
        // shift a body it already wrote.
        Pb.InventoryView pb = PbView(count, seed: count);
        Sgl.InventoryView sgl = ToSgl(pb);

        byte[] expected = pb.ToByteArray();
        Assert.Equal(expected, sgl.ToByteArray());

        Assert.True(Sgl.InventoryView.TryRead(expected, out var decoded));
        AssertEqual(pb, decoded!);
        Assert.Equal(pb, Pb.InventoryView.Parser.ParseFrom(sgl.ToByteArray()));
    }

    [Fact]
    public void InventoryView_WithAnAllDefaultItem_StillWritesTheElement()
    {
        // A repeated message element is written even when every field is default: the
        // element's existence is information.
        var pb = new Pb.InventoryView();
        pb.Items.Add(new Pb.ItemStack());
        var sgl = new Sgl.InventoryView();
        sgl.Items.Add(new Sgl.ItemStack());

        Assert.Equal(new byte[] { 0x0A, 0x00 }, pb.ToByteArray());
        Assert.Equal(pb.ToByteArray(), sgl.ToByteArray());
    }

    [Theory]
    [InlineData(-1)]   // view not set
    [InlineData(0)]    // view set but empty: written as a zero-length field
    [InlineData(2)]
    [InlineData(40)]
    public void InventoryChanged_Parity(int count)
    {
        var pb = new Pb.InventoryChanged();
        var sgl = new Sgl.InventoryChanged();
        if (count >= 0)
        {
            pb.View = PbView(count, seed: 4);
            sgl.View = ToSgl(pb.View);
        }

        byte[] expected = pb.ToByteArray();
        Assert.Equal(expected, sgl.ToByteArray());

        Assert.True(Sgl.InventoryChanged.TryRead(expected, out var decoded));
        if (count < 0)
        {
            Assert.Null(decoded!.View);
        }
        else
        {
            Assert.NotNull(decoded!.View);
            AssertEqual(pb.View, decoded.View!);
        }

        Assert.Equal(pb, Pb.InventoryChanged.Parser.ParseFrom(sgl.ToByteArray()));
    }

    // ── Unknown fields and wire-type mismatches ────────────────────────────────────

    /// <summary>
    /// Appends one unknown field of every proto3 wire type, with field numbers a future
    /// schema might use, small and large.
    /// </summary>
    private static byte[] WithUnknownFields(byte[] known, bool before)
    {
        var w = new Sgl.ProtoWriter();
        void Unknowns()
        {
            w.WriteUInt64Field(7, ulong.MaxValue);                     // 10-byte varint
            w.WriteFixed32Field(99, 0xDEADBEEF);
            w.WriteFixed64Field(1000, 0x0123456789ABCDEF);
            w.WriteStringField(Sgl.ProtoReader.MaxFieldNumber, "from the future");
            int t = w.BeginLengthDelimited(15);                         // an unknown nested message
            w.WriteUInt32Field(1, 5);
            w.EndLengthDelimited(t);
        }

        Unknowns();
        byte[] unknown = w.ToArray();
        return before ? unknown.Concat(known).ToArray() : known.Concat(unknown).ToArray();
    }

    [Theory]
    [InlineData(true)]
    [InlineData(false)]
    public void UnknownFields_AreSkipped_ExactlyAsProtocSkipsThem(bool before)
    {
        Pb.ItemStack stack = PbStack(9);
        byte[] stackBytes = WithUnknownFields(stack.ToByteArray(), before);
        Assert.True(Sgl.ItemStack.TryRead(stackBytes, out var s));
        AssertEqual(Pb.ItemStack.Parser.ParseFrom(stackBytes), s!);

        Pb.InventoryView view = PbView(5, seed: 2);
        byte[] viewBytes = WithUnknownFields(view.ToByteArray(), before);
        Assert.True(Sgl.InventoryView.TryRead(viewBytes, out var v));
        AssertEqual(Pb.InventoryView.Parser.ParseFrom(viewBytes), v!);

        var pickup = new Pb.PickupRequest { EntityId = "loot_7" };
        byte[] pickupBytes = WithUnknownFields(pickup.ToByteArray(), before);
        Assert.True(Sgl.PickupRequest.TryRead(pickupBytes, out var p));
        Assert.Equal(Pb.PickupRequest.Parser.ParseFrom(pickupBytes).EntityId, p!.EntityId);

        byte[] reqBytes = WithUnknownFields(Array.Empty<byte>(), before);
        Assert.True(Sgl.InventoryRequest.TryRead(reqBytes, out _));
        Pb.InventoryRequest.Parser.ParseFrom(reqBytes); // protoc accepts it too

        var equip = new Pb.EquipRequest { InstanceId = "i1", Slot = "head" };
        byte[] equipBytes = WithUnknownFields(equip.ToByteArray(), before);
        Assert.True(Sgl.EquipRequest.TryRead(equipBytes, out var e));
        Assert.Equal("i1", e!.InstanceId);
        Assert.Equal("head", e.Slot);
        Assert.Equal(equip, Pb.EquipRequest.Parser.ParseFrom(equipBytes).Clone().WithoutUnknowns());
    }

    [Fact]
    public void AKnownFieldWithTheWrongWireType_IsSkippedAsUnknown_LikeProtoc()
    {
        // ItemStack field 1 (string) sent as a varint, field 3 (uint32) sent as a string.
        var w = new Sgl.ProtoWriter();
        w.WriteUInt32Field(1, 42);
        w.WriteStringField(3, "not a number");
        w.WriteStringField(2, "potion");
        byte[] bytes = w.ToArray();

        Pb.ItemStack pb = Pb.ItemStack.Parser.ParseFrom(bytes);
        Assert.True(Sgl.ItemStack.TryRead(bytes, out var sgl));
        AssertEqual(pb, sgl!);
        Assert.Equal("", sgl!.InstanceId);
        Assert.Equal(0u, sgl.Quantity);
        Assert.Equal("potion", sgl.ItemId);
    }

    [Fact]
    public void RepeatedScalarField_LastOneWins_LikeProtoc()
    {
        var w = new Sgl.ProtoWriter();
        w.WriteStringField(1, "first");
        w.WriteUInt32Field(3, 5);
        w.WriteStringField(1, "second");
        w.WriteUInt32Field(3, 9);
        byte[] bytes = w.ToArray();

        Assert.True(Sgl.ItemStack.TryRead(bytes, out var sgl));
        AssertEqual(Pb.ItemStack.Parser.ParseFrom(bytes), sgl!);
        Assert.Equal("second", sgl!.InstanceId);
    }

    [Fact]
    public void RepeatedSingularMessageField_Merges_LikeProtoc()
    {
        var a = new Pb.InventoryChanged { View = PbView(2, 1) };
        var b = new Pb.InventoryChanged { View = PbView(1, 6) };
        byte[] bytes = a.ToByteArray().Concat(b.ToByteArray()).ToArray();

        Pb.InventoryChanged pb = Pb.InventoryChanged.Parser.ParseFrom(bytes);
        Assert.True(Sgl.InventoryChanged.TryRead(bytes, out var sgl));
        Assert.Equal(3, pb.View.Items.Count);
        AssertEqual(pb.View, sgl!.View!);
    }

    [Fact]
    public void A32BitFieldFromALongerVarint_KeepsTheLow32Bits_LikeProtoc()
    {
        var w = new Sgl.ProtoWriter();
        w.WriteTag(3, Sgl.ProtoWireType.Varint);
        w.WriteVarint(0x1_0000_0007UL);
        byte[] bytes = w.ToArray();

        Assert.True(Sgl.ItemStack.TryRead(bytes, out var sgl));
        Assert.Equal(Pb.ItemStack.Parser.ParseFrom(bytes).Quantity, sgl!.Quantity);
        Assert.Equal(7u, sgl.Quantity);
    }

    [Fact]
    public void InvalidUtf8_DecodesWithReplacementCharacters_LikeProtoc()
    {
        byte[] bytes = { 0x0A, 0x03, 0x61, 0xFF, 0x62 }; // field 1: "a", 0xFF, "b"
        Assert.True(Sgl.PickupRequest.TryRead(bytes, out var sgl));
        Assert.Equal(Pb.PickupRequest.Parser.ParseFrom(bytes).EntityId, sgl!.EntityId);
    }

    // ── Hostile input: false, never an exception ───────────────────────────────────

    public static TheoryData<string, byte[]> Malformed() => new()
    {
        { "truncated tag varint", new byte[] { 0x80 } },
        { "truncated length", new byte[] { 0x0A } },
        { "length past end", new byte[] { 0x0A, 0x05, 0x61 } },
        { "huge length", new byte[] { 0x0A, 0xFF, 0xFF, 0xFF, 0xFF, 0x0F } },
        { "field number zero", new byte[] { 0x02, 0x00 } },
        { "wire type 6", new byte[] { 0x0E, 0x00 } },
        { "wire type 7", new byte[] { 0x0F, 0x00 } },
        { "start group (proto3 never emits groups)", new byte[] { 0x0B, 0x0C } },
        { "end group", new byte[] { 0x0C } },
        { "11-byte varint", new byte[] { 0x18, 0x80, 0x80, 0x80, 0x80, 0x80, 0x80, 0x80, 0x80, 0x80, 0x80, 0x01 } },
        { "truncated fixed32", new byte[] { 0x7D, 0x01, 0x02 } },
        { "truncated fixed64", new byte[] { 0x79, 0x01, 0x02, 0x03 } },
        { "tag beyond 32 bits", new byte[] { 0x80, 0x80, 0x80, 0x80, 0x80, 0x01, 0x00 } },
    };

    [Fact]
    public void AMalformedNestedMessage_FailsTheWholeDecode()
    {
        // View field 1 holds 2 bytes that are themselves an ItemStack with field 1 claiming
        // 5 bytes. The outer length is fine; the inner one runs past its slice.
        byte[] bytes = { 0x0A, 0x02, 0x0A, 0x05 };
        Assert.False(Sgl.InventoryView.TryRead(bytes, out _));
        Assert.Throws<InvalidProtocolBufferException>(() => Pb.InventoryView.Parser.ParseFrom(bytes));

        byte[] pushed = { 0x0A, 0x04, 0x0A, 0x02, 0x0A, 0x05 };
        Assert.False(Sgl.InventoryChanged.TryRead(pushed, out _));
        Assert.Throws<InvalidProtocolBufferException>(() => Pb.InventoryChanged.Parser.ParseFrom(pushed));
    }

    [Theory]
    [MemberData(nameof(Malformed))]
    public void MalformedInput_IsRefused_NotThrown(string what, byte[] bytes)
    {
        _ = what;
        Assert.False(Sgl.ItemStack.TryRead(bytes, out var a));
        Assert.Null(a);
        Assert.False(Sgl.InventoryView.TryRead(bytes, out _));
        Assert.False(Sgl.InventoryChanged.TryRead(bytes, out _));
        Assert.False(Sgl.PickupRequest.TryRead(bytes, out _));
        Assert.False(Sgl.EquipRequest.TryRead(bytes, out _));
        Assert.False(Sgl.UnequipRequest.TryRead(bytes, out _));
        Assert.False(Sgl.UseItemRequest.TryRead(bytes, out _));
        Assert.False(Sgl.InventoryRequest.TryRead(bytes, out _));
    }

    [Fact]
    public void Fuzz_MutatedAndRandomPayloads_NeverThrow_AndAgreeWithProtocWheneverBothAccept()
    {
        var rng = new Random(20261002); // fixed seed: a failure must reproduce
        byte[] seedBytes = new Pb.InventoryChanged { View = PbView(6, 3) }.ToByteArray();
        int bothAccepted = 0;

        for (int iter = 0; iter < 20000; iter++)
        {
            byte[] input;
            switch (iter % 3)
            {
                case 0: // random bytes
                    input = new byte[rng.Next(0, 64)];
                    rng.NextBytes(input);
                    break;
                case 1: // a valid payload with a few bytes flipped
                    input = (byte[])seedBytes.Clone();
                    for (int k = rng.Next(1, 4); k > 0; k--) input[rng.Next(input.Length)] = (byte)rng.Next(256);
                    break;
                default: // a valid payload truncated
                    input = seedBytes.AsSpan(0, rng.Next(seedBytes.Length)).ToArray();
                    break;
            }

            bool sglOk = Sgl.InventoryChanged.TryRead(input, out var sgl);
            Pb.InventoryChanged? pb = null;
            try { pb = Pb.InventoryChanged.Parser.ParseFrom(input); }
            catch (InvalidProtocolBufferException) { }

            if (sglOk && pb != null)
            {
                bothAccepted++;
                Assert.Equal(pb.View == null, sgl!.View == null);
                if (pb.View != null) AssertEqual(pb.View, sgl.View!);
            }
            else if (sglOk)
            {
                // The SGL codec must never accept something protoc refuses.
                Assert.Fail($"SGL accepted a payload protoc refuses: {Convert.ToHexString(input)}");
            }
        }

        Assert.True(bothAccepted > 100, $"fuzz exercised too few accepted payloads ({bothAccepted})");
    }

    // ── Writer primitives against protoc's own encoder ─────────────────────────────

    [Theory]
    [InlineData(0L)]
    [InlineData(1L)]
    [InlineData(-1L)]
    [InlineData(63L)]
    [InlineData(-64L)]
    [InlineData(int.MaxValue)]
    [InlineData(int.MinValue)]
    [InlineData(long.MaxValue)]
    [InlineData(long.MinValue)]
    public void ScalarPrimitives_MatchCodedOutputStream(long v)
    {
        var w = new Sgl.ProtoWriter();
        w.WriteInt32Field(1, (int)v);
        w.WriteSInt32Field(2, (int)v);
        w.WriteSInt64Field(3, v);
        w.WriteInt64Field(4, v);
        w.WriteFloatField(5, (float)v);
        w.WriteFixed64Field(6, (ulong)v);
        w.WriteBoolField(7, v != 0);

        using var ms = new MemoryStream();
        var cos = new CodedOutputStream(ms);
        if ((int)v != 0) { cos.WriteTag(1, WireFormat.WireType.Varint); cos.WriteInt32((int)v); }
        if ((int)v != 0) { cos.WriteTag(2, WireFormat.WireType.Varint); cos.WriteSInt32((int)v); }
        if (v != 0) { cos.WriteTag(3, WireFormat.WireType.Varint); cos.WriteSInt64(v); }
        if (v != 0) { cos.WriteTag(4, WireFormat.WireType.Varint); cos.WriteInt64(v); }
        if (BitConverter.SingleToInt32Bits((float)v) != 0) { cos.WriteTag(5, WireFormat.WireType.Fixed32); cos.WriteFloat((float)v); }
        if (v != 0) { cos.WriteTag(6, WireFormat.WireType.Fixed64); cos.WriteFixed64((ulong)v); }
        if (v != 0) { cos.WriteTag(7, WireFormat.WireType.Varint); cos.WriteBool(true); }
        cos.Flush();

        Assert.Equal(ms.ToArray(), w.ToArray());

        var r = new Sgl.ProtoReader(w.ToArray());
        while (!r.IsAtEnd)
        {
            Assert.True(r.TryReadTag(out int field, out _));
            switch (field)
            {
                case 1: Assert.True(r.TryReadInt32(out int i32)); Assert.Equal((int)v, i32); break;
                case 2: Assert.True(r.TryReadSInt32(out int s32)); Assert.Equal((int)v, s32); break;
                case 3: Assert.True(r.TryReadSInt64(out long s64)); Assert.Equal(v, s64); break;
                case 4: Assert.True(r.TryReadVarint(out ulong u64)); Assert.Equal((ulong)v, u64); break;
                case 5: Assert.True(r.TryReadFloat(out float f)); Assert.Equal(BitConverter.SingleToInt32Bits((float)v), BitConverter.SingleToInt32Bits(f)); break;
                case 6: Assert.True(r.TryReadFixed64(out ulong f64)); Assert.Equal((ulong)v, f64); break;
                case 7: Assert.True(r.TryReadBool(out bool b)); Assert.True(b); break;
            }
        }
    }

    [Fact]
    public void NegativeZeroFloat_IsWritten_BecauseOnlyPositiveZeroIsTheDefault()
    {
        var w = new Sgl.ProtoWriter();
        w.WriteFloatField(1, -0f);
        Assert.Equal(new byte[] { 0x0D, 0x00, 0x00, 0x00, 0x80 }, w.ToArray());
    }

    [Fact]
    public void Writer_IsReusableAfterReset()
    {
        var w = new Sgl.ProtoWriter(16);
        new Sgl.PickupRequest { EntityId = new string('q', 300) }.Write(w);
        w.Reset();
        new Sgl.PickupRequest { EntityId = "x" }.Write(w);
        Assert.Equal(new Pb.PickupRequest { EntityId = "x" }.ToByteArray(), w.ToArray());
    }

    [Fact]
    public void Opcodes_AndErrorCodes_AreTheDocumentedValues()
    {
        Assert.Equal(1u, Sgl.GameplayOpcodes.Inventory);
        Assert.Equal(2u, Sgl.GameplayOpcodes.Pickup);
        Assert.Equal(3u, Sgl.GameplayOpcodes.Equip);
        Assert.Equal(4u, Sgl.GameplayOpcodes.Unequip);
        Assert.Equal(5u, Sgl.GameplayOpcodes.UseItem);
        Assert.Equal(100u, Sgl.GameplayOpcodes.InventoryChanged);
        Assert.False(Sgl.GameplayOpcodes.IsKnownRequest(0));
        Assert.False(Sgl.GameplayOpcodes.IsKnownRequest(100));
        Assert.True(Sgl.GameplayOpcodes.IsKnownPush(100));

        Assert.Equal("unknown_opcode", Sgl.GameplayErrors.UnknownOpcode);
        Assert.Equal("invalid_payload", Sgl.GameplayErrors.InvalidPayload);
        Assert.Equal("rate_limited", Sgl.GameplayErrors.RateLimited);
        Assert.Equal("not_found", Sgl.GameplayErrors.NotFound);
        Assert.Equal("out_of_range", Sgl.GameplayErrors.OutOfRange);
        Assert.Equal("slot_mismatch", Sgl.GameplayErrors.SlotMismatch);
        Assert.Equal("inventory_full", Sgl.GameplayErrors.InventoryFull);
        Assert.Equal("not_owner", Sgl.GameplayErrors.NotOwner);
    }
}

internal static class PbTestExtensions
{
    /// <summary>
    /// A copy with unknown fields dropped, so equality compares only the schema's fields
    /// (protoc preserves unknown fields; the SGL codec, by design, does not).
    /// </summary>
    public static Pb.EquipRequest WithoutUnknowns(this Pb.EquipRequest m) =>
        new() { InstanceId = m.InstanceId, Slot = m.Slot };
}
